DROP TABLE user_roles IF EXISTS;
DROP TABLE products IF EXISTS CASCADE ;
DROP TABLE users IF EXISTS;
DROP TABLE images IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  email            VARCHAR(255)            NOT NULL,
  password         VARCHAR(255)            NOT NULL,
  registered       TIMESTAMP DEFAULT now() NOT NULL,
  enabled          BOOLEAN DEFAULT TRUE    NOT NULL,
  phone            VARCHAR(255)         NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
  ON USERS (email);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE products
(
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  time        INTEGER  NOT NULL,
  description VARCHAR(255)      NOT NULL,
  price    INTEGER       NOT NULL
);
CREATE UNIQUE INDEX entities_unique_user_id_idx
  ON products (id);
CREATE TABLE images (
                        id INTEGER PRIMARY KEY NOT NULL ,
                        product_id INTEGER NOT NULL ,
                        image VARCHAR(255) NOT NULL,
                        FOREIGN KEY (product_id)REFERENCES products(id) ON DELETE  CASCADE );